version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: payroll-postgres
    restart: always
    environment:
      POSTGRES_USER: payroll_user
      POSTGRES_PASSWORD: payroll_password
      POSTGRES_DB: payrollDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payroll-net

volumes:
  postgres_data:

networks:
  payroll-net:
    driver: bridge